### ISSUE TITLE
ClassCastException com.sun.tools.javac.code.Symbol$MethodSymbol cannot be cast to javax.lang.model.element.VariableElement

### ISSUE THREAD

**Issue by rimmer** [hamsterksu/annotatedsql-projection-plugin#1]
When trying to make project, getting `java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$MethodSymbol cannot be cast to javax.lang.model.element.VariableElement` [here](https://github.com/hamsterksu/annotatedsql-projection-plugin/blob/master/projection-plugin-processor/src/main/java/com/hamsterksu/asql/projections/ProjectionPlugin.java#L147)

I tried using Oracle JDK 8 instead of JDK 7, and also tried OpenJDK 7, compiled under Windows, and I failed. 
Let me know, if you need stacktrace.

My environment:
OS: Windows 8.1 x64
IDE: Android Studio 1.0 RC2 (reproduced on earlier versions)
Gradle 2.2.1 (reproduced on earlier versions, ex 2.1)
Android gradle plugin: 0.14.2
AnnotatedSQL version: 1.10.3

Projection plugin included using aptlibs 1.2.0.

**Comment by hamsterksu** [comment]
Hi, 
it's very strange. i uses windows + jdk1.7.0. evreging is ok.
 i will check on java 8

**Comment by hamsterksu** [comment]
Coudl you share your code to reproduce issue? 
`Symbol$MethodSymbol` is `ExecutableElement`, looks like you assign `@Projection` to a method.
You should assing it to constant 

``` java
@Projection({TableName.COLUMN1, TableName.COLUMN2, TableName.COLUMN3})
String PROJECTION_TEST = "POST_TEST";
```

**Comment by hamsterksu** [comment]
works on windows 7 + android plugin 0.14.4 + oracle jdk 8. will wait for your code

**Comment by rimmer** [comment]
I'm doing like this:

```
@Projection
public static final String ALL = "All";
```

I'm using `@Projection` inside a class, not inside an interface, maybe the problem is somewhere near... 
The full code:

```
@Schema(className = "VParkSchema", dbName = "database.db", dbVersion = 1)
@Provider(authority = BuildConfig.AUTHORITY, schemaClass = "VParkSchema", name = "VParkProvider")
public interface DataStore {
// .... other classes
@Table(Country.TABLE_NAME)
public class Country implements BaseColumns, ItemSaveable {
    public static final String TABLE_NAME = "countries";

    @URI
    public static final String CONTENT_URI = TABLE_NAME;

    @Column
    public static final String NAME = "name";

    @Column
    public static final String ISO_ID = "iso_id";

    @Projection
    public static final String ALL = "All";

    @Expose
    private String name;
    @Expose
    private String id;

    /**
     *
     * @return
     * The name
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @param name
     * The name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return
     * The code
     */
    public String getId() {
        return id;
    }

    /**
     *
     * @param id
     * The code
     */
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public ContentValues toValues() {
        ContentValues values = new ContentValues(2);
        values.put(NAME, name);
        values.put(ISO_ID, id);
        return values;
    }
}
}
```

**Comment by rimmer** [comment]
Yep, the problem was with using class instead of interface. Maybe the lib should warn somehow that using class is incorrect or work normally with class.
